spring.application.name=CoreBackend


server.port=8085


## JPA and Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/corebackenddb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
##
## this is for development purpose only, in production we should use flyway or liquibase to manage database schema changes and migrations
##spring.jpa.hibernate.ddl-auto=update
##

spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
## spring.jpa.show-sql=true === similar to logging.level.org.hibernate.SQL=DEBUG, but this is not recommended for production as it can log sensitive data



##logging configuration
logging.level.org.springframework=INFO
logging.level.com.io.CoreBackend=DEBUG
logging.level.org.hibernate.SQL=DEBUG


##Actuator configuration
management.endpoints.web.exposure.include=health,info,metrics,env,beans,mappings,loggers

###
### this is for development purpose only, in production we should use management.endpoint.health.show-details=when-authorized
# and
# management.endpoint.health.roles=ADMIN to restrict health endpoint details to authorized users only
###
##management.endpoint.health.show-details=always
management.endpoint.health.show-details=when-authorized
management.endpoint.health.roles=ADMIN
###




info.app.name=CoreBackend
info.app.description=Book CRUD learning project

## Security Configuration
## JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

spring.jpa.open-in-view=false


